library(tidyverse)
library(scales)
library(rvest)
library(lubridate)
library(readr)


# reading all csv files generated by votes_scraper.py
votes121 <- read_csv("../data/votes/votes_121.csv")
votes122 <- read_csv("../data/votes/votes_122.csv")
votes123 <- read_csv("../data/votes/votes_123.csv")
votes124 <- read_csv("../data/votes/votes_124.csv")
votes125 <- read_csv("../data/votes/votes_125.csv")
votes126 <- read_csv("../data/votes/votes_126.csv")
votes127 <- read_csv("../data/votes/votes_127.csv")
votes128 <- read_csv("../data/votes/votes_128.csv")
votes129 <- read_csv("../data/votes/votes_129.csv")
votes130 <- read_csv("../data/votes/votes_130.csv")
votes131 <- read_csv("../data/votes/votes_131.csv")
votes132 <- read_csv("../data/votes/votes_132.csv")
votes133 <- read_csv("../data/votes/votes_133.csv")
votes134 <- read_csv("../data/votes/votes_134.csv")
votes135 <- read_csv("../data/votes/votes_135.csv")
votes136 <- read_csv("../data/votes/votes_136.csv")
votes137 <- read_csv("../data/votes/votes_137.csv")
votes138 <- read_csv("../data/votes/votes_138.csv")
votes139 <- read_csv("../data/votes/votes_139.csv")
votes140 <- read_csv("../data/votes/votes_140.csv")
votes141 <- read_csv("../data/votes/votes_141.csv")
votes142 <- read_csv("../data/votes/votes_142.csv")
votes143 <- read_csv("../data/votes/votes_143.csv")
votes144 <- read_csv("../data/votes/votes_144.csv")
votes145 <- read_csv("../data/votes/votes_145.csv")
votes146 <- read_csv("../data/votes/votes_146.csv")
votes147 <- read_csv("../data/votes/votes_147.csv")
votes148 <- read_csv("../data/votes/votes_148.csv")

# merging all csv files into all_votes
all_votes <- Reduce(function(x,y) merge(x,y, all=TRUE), list(votes121,
                                                             votes122,
                                                             votes123,
                                                             votes124,
                                                             votes125,
                                                             votes126,
                                                             votes127,
                                                             votes128,
                                                             votes129,
                                                             votes130,
                                                             votes131,
                                                             votes132,
                                                             votes133,
                                                             votes134,
                                                             votes135,
                                                             votes136,
                                                             votes137,
                                                             votes138,
                                                             votes139,
                                                             votes140,
                                                             votes141,
                                                             votes142,
                                                             votes143,
                                                             votes144,
                                                             votes145,
                                                             votes146,
                                                             votes147,
                                                             votes148)) %>% 
  filter(vote != "f: óþekktur kóði") # steingrímur J. 1 vote where he either was 'fjarverandi' or 'boðaði fjarvist'

# reading member details from csv
members <- read_csv("../data/members_details.csv") %>%
  select(member_id, party_id, congress) %>% distinct

# reading party details from csv

# mergeing all votes with member data
all_votes_with_members <- all_votes %>% 
  merge(members, votes, by = c("member_id", "congress"))

# calculating datetime for each vote
all_votes$time <- sprintf("%s:%s:%s", all_votes$vote_time_hour, all_votes$vote_time_minute, all_votes$vote_time_second)
all_votes$date <- sprintf("%s-%s-%s", all_votes$vote_time_year, all_votes$vote_time_month, all_votes$vote_time_date)
all_votes$dateTime <- with(all_votes, as.POSIXct(paste(date, time), format="%Y-%m-%d %H:%M:%S"))

# REMOVE
all_votes <- votes121_148 # FOR TESTING

# calculate totals each year, month, day, hour
# Yes calculations
# calculate total yes per year
total_yes_year <- all_votes %>%
  filter(vote == "já") %>%
  group_by(vote_time_year, vote) %>%
  summarise(total_yes_year=n())
# merge total yes with all_votes
all_votes <- merge(all_votes, total_yes_year, all=TRUE)
# calculate total yes per month
total_yes_month <- all_votes %>%
  filter(vote == "já") %>%
  group_by(vote_time_month, vote) %>%
  summarise(total_yes_month=n())
# merge total yes with all_votes
all_votes <- merge(all_votes, total_yes_month, all=TRUE)
# calculate total yes per day
total_yes_day <- all_votes %>%
  filter(vote == "já") %>%
  group_by(vote_time_date, vote) %>%
  summarise(total_yes_day=n())
# merge total yes with all_votes
all_votes <- merge(all_votes, total_yes_day, all=TRUE)
# calculate total yes per hour
total_yes_hour <- all_votes %>%
  filter(vote == "já") %>%
  group_by(vote_time_hour, vote) %>%
  summarise(total_yes_hour=n())
# merge total yes with all_votes
all_votes <- merge(all_votes, total_yes_hour, all=TRUE)
# No calculations
# calculate total no per year
total_no_year <- all_votes %>%
  filter(vote == "nei") %>%
  group_by(vote_time_year, vote) %>%
  summarise(total_no_year=n())
# merge total no with all_votes
all_votes <- merge(all_votes, total_no_year, all=TRUE)
# calculate total no per month
total_no_month <- all_votes %>%
  filter(vote == "nei") %>%
  group_by(vote_time_month, vote) %>%
  summarise(total_no_month=n())
# merge total no with all_votes
all_votes <- merge(all_votes, total_no_month, all=TRUE)
# calculate total no per day
total_no_day <- all_votes %>%
  filter(vote == "nei") %>%
  group_by(vote_time_date, vote) %>%
  summarise(total_no_day=n())
# merge total no with all_votes
all_votes <- merge(all_votes, total_no_day, all=TRUE)
# calculate total no per hour
total_no_hour <- all_votes %>%
  filter(vote == "nei") %>%
  group_by(vote_time_hour, vote) %>%
  summarise(total_no_hour=n())
# merge total no with all_votes
all_votes <- merge(all_votes, total_no_hour, all=TRUE)
# Total did not vote calculations
# calculate total did_not_vote per year
total_did_not_vote_year <- all_votes %>%
  filter(vote == "greiðir ekki atkvæði") %>%
  group_by(vote_time_year, vote) %>%
  summarise(total_did_not_vote_year=n())
# merge total did_not_vote with all_votes
all_votes <- merge(all_votes, total_did_not_vote_year, all=TRUE)
# calculate total did_not_vote per month
total_did_not_vote_month <- all_votes %>%
  filter(vote == "greiðir ekki atkvæði") %>%
  group_by(vote_time_month, vote) %>%
  summarise(total_did_not_vote_month=n())
# merge total did_not_vote with all_votes
all_votes <- merge(all_votes, total_did_not_vote_month, all=TRUE)
# calculate total did_not_vote per day
total_did_not_vote_day <- all_votes %>%
  filter(vote == "greiðir ekki atkvæði") %>%
  group_by(vote_time_date, vote) %>%
  summarise(total_did_not_vote_day=n())
# merge total did_not_vote with all_votes
all_votes <- merge(all_votes, total_did_not_vote_day, all=TRUE)
# calculate total did_not_vote per hour
total_did_not_vote_hour <- all_votes %>%
  filter(vote == "greiðir ekki atkvæði") %>%
  group_by(vote_time_hour, vote) %>%
  summarise(total_did_not_vote_hour=n())
# merge total did_not_vote with all_votes
all_votes <- merge(all_votes, total_did_not_vote_hour, all=TRUE)
# Total did not attend calculations
# calculate total did_not_attend per year
total_did_not_attend_year <- all_votes %>%
  filter(vote == "fjarverandi") %>%
  group_by(vote_time_year, vote) %>%
  summarise(total_did_not_attend_year=n())
# merge total did_not_attend with all_votes
all_votes <- merge(all_votes, total_did_not_attend_year, all=TRUE)
# calculate total did_not_attend per month
total_did_not_attend_month <- all_votes %>%
  filter(vote == "fjarverandi") %>%
  group_by(vote_time_month, vote) %>%
  summarise(total_did_not_attend_day=n())
# merge total did_not_attend with all_votes
all_votes <- merge(all_votes, total_did_not_attend_month, all=TRUE)
# calculate total did_not_attend per day
total_did_not_attend_day <- all_votes %>%
  filter(vote == "fjarverandi") %>%
  group_by(vote_time_date, vote) %>%
  summarise(total_did_not_attend_day=n())
# merge total did_not_attend with all_votes
all_votes <- merge(all_votes, total_did_not_attend_day, all=TRUE)
# calculate total did_not_attend per hour
total_did_not_attend_hour <- all_votes %>%
  filter(vote == "fjarverandi") %>%
  group_by(vote_time_hour, vote) %>%
  summarise(total_did_not_attend_hour=n())
# merge total did_not_attend with all_votes
all_votes <- merge(all_votes, total_did_not_attend_hour, all=TRUE)
# Total boðaði fjarvist calculations
# calculate total reported_leave per year
total_reported_leave_year <- all_votes %>%
  filter(vote == "boðaði fjarvist") %>%
  group_by(vote_time_year, vote) %>%
  summarise(total_reported_leave_year=n())
# merge total reported_leave with all_votes
all_votes <- merge(all_votes, total_reported_leave_year, all=TRUE)
# calculate total reported_leave per month
total_reported_leave_month <- all_votes %>%
  filter(vote == "boðaði fjarvist") %>%
  group_by(vote_time_month, vote) %>%
  summarise(total_reported_leave_month=n())
# merge total reported_leave with all_votes
all_votes <- merge(all_votes, total_reported_leave_month, all=TRUE)
# calculate total reported_leave per day
total_reported_leave_day <- all_votes %>%
  filter(vote == "boðaði fjarvist") %>%
  group_by(vote_time_date, vote) %>%
  summarise(total_reported_leave_day=n())
# merge total reported_leave with all_votes
all_votes <- merge(all_votes, total_reported_leave_day, all=TRUE)
# calculate total reported_leave per hour
total_reported_leave_hour <- all_votes %>%
  filter(vote == "boðaði fjarvist") %>%
  group_by(vote_time_hour, vote) %>%
  summarise(total_reported_leave_hour=n())
# merge total reported_leave with all_votes
all_votes <- merge(all_votes, total_reported_leave_hour, all=TRUE)

# remove extra values genereted with calculations
all_votes <- all_votes %>% 
  filter(!is.na(vote_id))


# write all_votes to csv
write.csv(all_votes, file="../data/votes/votes_121-148.csv", fileEncoding="UTF-8", row.names=FALSE)
rm(list=ls())

# read mega csv
votes121_148 <- read_csv("../data/votes/votes_121-148.csv") 

special <- votes121_148 %>% 
  filter(vote_id==54196) %>% 
  group_by(vote_id, vote) %>% 
  summarise(count=n())


  

votes121_148 %>%
  #filter(vote == "fjarverandi" | vote == "boðaði fjarvist") %>% 
  filter(vote_time_year != max(vote_time_year) & vote_time_year != min(vote_time_year)) %>%
  #group_by(vote_time_year, vote) %>% 
  #summarise(sum=n()) %>% 
  ggplot() +
  #geom_smooth(mapping = aes(x=vote_time_year, y=sum, color=vote)) +
  geom_bar(mapping = aes(x=vote_time_year, fill=vote), position = "fill")+
  scale_y_continuous(breaks = c(0, 0.25, 0.5, 0.75, 1), labels = scales::percent(c(0, 0.25, 0.5, 0.75, 1))) +
  #scale_x_datetime(breaks=date_breaks("2 year"), labels=date_format("%Y")) +
  scale_x_continuous(breaks = seq(1997,2017,by=2)) +
  theme_bw()+
  labs(
    title = "Attendance Throughout the Years",
    subtitle="Data for years 1997-2017",
    y = "",
    x = "Year",
    fill = "Vote"
  ) +
  scale_fill_manual(values = c('#999999',
                               '#666666',
                               '#F0E442',
                               '#009E73',
                               '#D55E00',
                               '#992222'))

